# Generated by Django 4.0.6 on 2022-07-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qapps', '0002_rename_question_questions_rename_reply_replys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='replys',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
